force-app/main/default/objects/BenchmarkJobSetting__mdt/BenchmarkJobSetting__mdt.object-meta.xml
<CustomObject>
    <description>Includes configuration details for a single instance of a benchmark job.</description>
    <label>Benchmark Job Setting</label>
    <pluralLabel>Benchmark Job Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>When checked, the job is eligible to run when called.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <inlineHelpText
	>The fully qualified API name of an Apex Class. An instance of this class will be instantiated and executed during the given benchmark job.
This Apex Class must implements the &quot;Benchmarkable&quot; interface, and have a publicly visible, 0-arg constructor.</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Describe the operation being benchmarked by the current job.</inlineHelpText>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/ExcludedSandboxes__c.field-meta.xml
<CustomField>
    <fullName>ExcludedSandboxes__c</fullName>
    <inlineHelpText
	>A comma-separated list of sandbox domain names (ex., &quot;full&quot;, &quot;partial&quot;, &quot;uat&quot;, etc.) that will be excluded from processing. 
Use this field to prevent the job from running in certain sandboxes, if desired. 
To prevent the job from running in a production environment, set the &quot;Run In Production&quot; field to false.</inlineHelpText>
    <label>Excluded Sandbox(es)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <inlineHelpText>Details the type of operation being performed during benchmarking</inlineHelpText>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API Call</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Lead Convert</fullName>
            </value>
            <value>
                <fullName>Merge</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Undelete</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Upsert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/RunInProduction__c.field-meta.xml
<CustomField>
    <fullName>RunInProduction__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText
	>When checked, this Benchmark Job may be permitted to run in production environments. Use caution, as this may have unintended consequences.</inlineHelpText>
    <label>Run in Production?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <inlineHelpText>The type of SObject being benchmarked by the current job.</inlineHelpText>
    <label>SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>BenchmarkJobSettings</relationshipLabel>
    <relationshipName>BenchmarkJobSettings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/BenchmarkJobSettingSelector.cls
public without sharing abstract class BenchmarkJobSettingSelector {
	@TestVisible
	private static Map<String, BenchmarkJobSetting__mdt> settings;

	public static Map<String, BenchmarkJobSetting__mdt> getAll() {
		settings = settings ?? BenchmarkJobSettingSelector.retrieveFromOrg();
		System.debug(LoggingLevel.FINEST, 'All BenchmarkJobSetting__mdt: ' + settings?.values());
		return settings;
	}

	public static Map<String, BenchmarkJobSetting__mdt> get(Set<String> settingNames) {
		Map<String, BenchmarkJobSetting__mdt> results = new Map<String, BenchmarkJobSetting__mdt>();
		for (String settingName : settingNames) {
			BenchmarkJobSetting__mdt setting = BenchmarkJobSettingSelector.getAll()?.get(settingName);
			if (setting != null) {
				results?.put(settingName, setting);
			}
		}
		return results;
	}

	public static BenchmarkJobSetting__mdt get(String developerName) {
		return BenchmarkJobSettingSelector.get(new Set<String>{ developerName })?.get(developerName);
	}

	@TestVisible
	private static Map<String, BenchmarkJobSetting__mdt> mapByDeveloperName(List<BenchmarkJobSetting__mdt> settings) {
		Map<String, BenchmarkJobSetting__mdt> settingsMap = new Map<String, BenchmarkJobSetting__mdt>();
		for (BenchmarkJobSetting__mdt setting : settings) {
			String developerName = setting?.DeveloperName;
			settingsMap?.put(setting?.DeveloperName, setting);
		}
		return settingsMap;
	}

	private static List<BenchmarkJobSetting__mdt> querySettings() {
		return [
			SELECT
				Id,
				Active__c,
				ApexClass__c,
				Description__c,
				DeveloperName,
				ExcludedSandboxes__c,
				MasterLabel,
				Operation__c,
				RunInProduction__c,
				SObjectType__r.QualifiedApiName
			FROM BenchmarkJobSetting__mdt
			WITH SYSTEM_MODE
		];
	}

	private static Map<String, BenchmarkJobSetting__mdt> retrieveFromOrg() {
		List<BenchmarkJobSetting__mdt> settings = BenchmarkJobSettingSelector.querySettings();
		return BenchmarkJobSettingSelector.mapByDeveloperName(settings);
	}
}