force-app/main/default/objects/BenchmarkJobSetting__mdt/BenchmarkJobSetting__mdt.object-meta.xml
<CustomObject>
    <description>Includes configuration details for a single instance of a benchmark job.</description>
    <label>Benchmark Job Setting</label>
    <pluralLabel>Benchmark Job Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>When checked, the job is eligible to run when called.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <inlineHelpText
	>The fully qualified API name of an Apex Class. An instance of this class will be instantiated and executed during the given benchmark job.
This Apex Class must implements the &quot;Benchmarkable&quot; interface, and have a publicly visible, 0-arg constructor.</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/RunInProduction__c.field-meta.xml
<CustomField>
    <fullName>RunInProduction__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText
	>When checked, this Benchmark Job may be permitted to run in production environments. Use caution, as this may have unintended consequences.</inlineHelpText>
    <label>Run in Production?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BenchmarkTestUtils.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
@IsTest
global class BenchmarkTestUtils {
	global static BenchmarkJobSetting__mdt initSetting(Type apexClass, String developerName) {
		// Initialize a new setting record for testing
		BenchmarkJobSetting__mdt setting = new BenchmarkJobSetting__mdt(
			Active__c = true,
			ApexClass__c = apexClass?.toString(),
			DeveloperName = developerName,
			RunInProduction__c = true
		);
		BenchmarkTestUtils.inject(setting);
		return setting;
	}

	global static BenchmarkJobSetting__mdt initSetting(Type apexClass) {
		return BenchmarkTestUtils.initSetting(apexClass, apexClass?.toString());
	}

	private static void inject(BenchmarkJobSetting__mdt setting) {
		// Inject the test record into the cache of settings to be used in place of actual cmdt records
		String developerName = setting?.DeveloperName;
		BenchmarkTestUtils.useMockSettings()?.put(developerName, setting);
	}

	private static Map<String, BenchmarkJobSetting__mdt> useMockSettings() {
		// Ensure the BenchmarkJobSettingSelector uses mock/injected settings for testing,
		// and not "real" cmdt records that actually exist in the org
		BenchmarkJobSettingSelector.settings = (BenchmarkJobSettingSelector.settings != null)
			? BenchmarkJobSettingSelector.settings
			: new Map<String, BenchmarkJobSetting__mdt>();
		return BenchmarkJobSettingSelector.settings;
	}
}