force-app/main/default/objects/Benchmark__c/Benchmark__c.object-meta.xml
<CustomObject>
    <description
	>Used by Salesforce Development teams to measure org health and performance. Each record represents the performance of a specific operation at a specific point in time.</description>
    <label>Benchmark</label>
    <nameField>
        <displayFormat>B-{000000000}</displayFormat>
        <label>Benchmark Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benchmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Benchmark__c/fields/BenchmarkCompletedAt__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkCompletedAt__c</fullName>
    <description
	>Indicates the time in the job run that the benchmark() method was completed. This is used to calculate Benchmark Duration.</description>
    <label>Benchmark Completed At (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/BenchmarkStartedAt__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkStartedAt__c</fullName>
    <description
	>Indicates the time in the job run that the benchmark() method was called. This is used to calculate Benchmark Duration.</description>
    <label>Benchmark Started At (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Displays the error type, if any exceptions were thrown during the benchmark job.</description>
    <label>Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/ErrorDetail__c.field-meta.xml
<CustomField>
    <fullName>ErrorDetail__c</fullName>
    <description
	>The full error detail, including message and stack trace, of any exceptions thrown during job execution.</description>
    <label>Error Detail</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/SetupCompletedAt__c.field-meta.xml
<CustomField>
    <fullName>SetupCompletedAt__c</fullName>
    <inlineHelpText
	>Indicates the time in the job run that the setup() method finished running. This is used to calculate Setup Duration.</inlineHelpText>
    <label>Setup Completed At (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/SetupStartedAt__c.field-meta.xml
<CustomField>
    <fullName>SetupStartedAt__c</fullName>
    <inlineHelpText
	>Indicates the time in the job run that the setup() method was called. This is used to calculate &quot;Setup Duration&quot;.</inlineHelpText>
    <label>Setup Started At (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BenchmarkJobSetting__mdt/BenchmarkJobSetting__mdt.object-meta.xml
<CustomObject>
    <description>Includes configuration details for a single instance of a benchmark job.</description>
    <label>Benchmark Job Setting</label>
    <pluralLabel>Benchmark Job Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/BenchmarkJobSetting__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>When checked, the job is eligible to run when called.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BenchmarkJob.cls
public without sharing class BenchmarkJob implements System.Queueable, System.Finalizer {
	@TestVisible
	private static Environment environment = new Environment();

	private Benchmark__c benchmarkRecord;
	private BenchmarkJobSetting__mdt currentJob;
	private Map<String, BenchmarkJobSetting__mdt> pending;

	public BenchmarkJob() {
		this.pending = BenchmarkJobSettingSelector.getAll();
		this.getNext();
	}

	public void execute(System.QueueableContext context) {
		System.attachFinalizer(this);
		// Is the Benchmark job enabled? If not, terminate the job
		if (this.shouldRun() == true) {
			// Instantiate a Benchmark__c record using the settings record
			this.benchmarkRecord = this.initBenchmarkRecord();
			// Create an instance of the Benchmarkable instance
			Benchmarkable instance = this.initBenchmarkable();
			// Run the setup method
			this.doSetup(instance);
			// Run the benchmark method
			this.doBenchmark(instance);
		}
	}

	public void execute(System.FinalizerContext context) {
		try {
			// Prevent inserting empty benchmark records
			if (this.benchmarkRecord != null) {
				this.captureErrorDetails(context);
				Database.insert(this.benchmarkRecord, System.AccessLevel.SYSTEM_MODE);
			}
			// Launch the next iteration of the job
			this.getNext()?.launch();
		} catch (Exception error) {
			System.debug(System.LoggingLevel.ERROR, error);
		}
	}

	public Id launch() {
		if (this.currentJob != null) {
			Id jobId = System.enqueueJob(this);
			System.debug(System.LoggingLevel.INFO, 'Launching new job: ' + jobId);
			return jobId;
		} else {
			return null;
		}
	}

	private void doBenchmark(Benchmarkable instance) {
		this.benchmarkRecord.BenchmarkStartedAt__c = Limits.getCpuTime();
		instance?.benchmark();
		this.benchmarkRecord.BenchmarkCompletedAt__c = Limits.getCpuTime();
	}

	private void doSetup(Benchmarkable instance) {
		// Run the current instance's setup method
		this.benchmarkRecord.SetupStartedAt__c = Limits.getCpuTime();
		instance?.setup();
		this.benchmarkRecord.SetupCompletedAt__c = Limits.getCpuTime();
	}

	private BenchmarkJob getNext() {
		// Get the next BenchmarkJobSetting__mdt to process
		String jobName = (this.pending?.isEmpty() == false) ? this.pending?.values()?.get(0)?.DeveloperName : null;
		this.currentJob = BenchmarkJobSettingSelector.get(jobName);
		// Remove the currentJob job from the list of pending jobs
		this.pending?.remove(jobName);
		// Validate that the job's settings record is still active
		if (this.currentJob?.Active__c == false) {
			// If so, skip the currentJob job, and recurse to find the next job in the chain
			System.debug(System.LoggingLevel.FINEST, 'Skipping inactive job');
			this.getNext();
		}
		System.debug(System.LoggingLevel.FINEST, 'Next GarbageCollector__mdt job: ' + this.currentJob?.DeveloperName);
		System.debug(System.LoggingLevel.FINEST, 'Pending GarbageCollector__mdt jobs: ' + this.pending?.keySet());
		return this;
	}

	private Benchmark__c initBenchmarkRecord() {
		// Create a benchmark record based on the details of the corresponding cmdt record
		return new Benchmark__c(); // TODO!
	}

	private Benchmarkable initBenchmarkable() {
		// Initialize a Benchmarkable instance, using the apex class name stored in the cmdt
		return null; // TODO!
	}

	private void captureErrorDetails(System.FinalizerContext context) {
		// Record any errors that resulted in the process
		if (context?.getResult() == System.ParentJobResult.UNHANDLED_EXCEPTION) {
			System.Exception error = context?.getException();
			this.benchmarkRecord.Error__c = error?.getTypeName();
			this.benchmarkRecord.ErrorDetail__c = String.join(
				new List<String>{ error?.getMessage(), error?.getStackTraceString() },
				'\n'
			);
		}
	}

	private Boolean shouldRun() {
		// Returns true if the current job is eligible to be run
		// Returns false if Inactive,
		// or in an excluded sandbox,
		// or if in a production environment w/"Run in Production" set to false
		return true; // TODO!
	}

	// **** INNER **** //
	public virtual class Environment {
		public virtual String getSandboxName() {
			System.Url url = System.Url.getOrgDomainUrl();
			return System.DomainParser.parse(url)?.getSandboxName();
		}

		public Boolean isSandbox() {
			return this.getSandboxName() != null;
		}
	}
}