force-app/main/default/objects/Benchmark__c/Benchmark__c.object-meta.xml
<CustomObject>
    <description
	>Used by Salesforce Development teams to measure org health and performance. Each record represents the performance of a specific operation at a specific point in time.</description>
    <label>Benchmark</label>
    <nameField>
        <displayFormat>B-{000000000}</displayFormat>
        <label>Benchmark Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benchmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Benchmark__c/fields/BenchmarkStartedAt__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkStartedAt__c</fullName>
    <description
	>Indicates the time in the job run that the benchmark() method was called. This is used to calculate Benchmark Duration.</description>
    <label>Benchmark Started At (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/SetupCompletedAt__c.field-meta.xml
<CustomField>
    <fullName>SetupCompletedAt__c</fullName>
    <inlineHelpText
	>Indicates the time in the job run that the setup() method finished running. This is used to calculate Setup Duration.</inlineHelpText>
    <label>Setup Completed At (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvocableStartBenchmarkTest.cls
@IsTest
private class InvocableStartBenchmarkTest {
	@IsTest
	static void shouldStampBenchmarkStartTime() {
		Benchmark__c record = new Benchmark__c();
		InvocableStartBenchmark.currentRecord = record;

		Test.startTest();
		InvocableStartBenchmark.invoke();
		Test.stopTest();

		Assert.areNotEqual(null, record?.SetupCompletedAt__c, 'Missing SetupCompletedAt__c');
		Assert.areNotEqual(null, record?.BenchmarkStartedAt__c, 'Missing BenchmarkStartedAt__c');
		Assert.areEqual(null, InvocableStartBenchmark.currentRecord, 'Did not remove pointer');
	}
}